### ISSUE TITLE
Highlighting breaks when using lambda syntax

### ISSUE THREAD

**Issue by maziarz** [atom/language-python#195] opened 2017-04-22 09:48 UTC
The highlighting breaks when using lambda expressions in functions.

```python
def test(variable) -> Response:
    print('this is a test')
```

Highlights to:

![Image of highlighting issue](http://i64.tinypic.com/2cpozmq.png)

> language-python: 0.45.2

> atom --version
> Atom    : 1.15.0
> Electron: 1.3.13
> Chrome  : 52.0.2743.82
> Node    : 6.5.0

> apm --version
> apm  1.15.3
> npm  3.10.5
> node 4.4.5 x64
> python 2.7.8
> git 2.7.4

> OS: OSX 10.11.1

**Comment by 50Wliu** [comment] 2018-01-22 02:19
Duplicate of #68.

**Closed by 50Wliu** 2018-01-22 02:19 UTC
Labels: bug
