### ISSUE TITLE
Syntax highlighting broke in certain cases

### ISSUE THREAD

**Issue by kingbuzzman** [atom/language-python#196] opened 2017-04-27 23:00 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Syntax color is breaking.

### Steps to Reproduce

1. Have language-python installed
2. Have a file with comments like this

```
import sys
import os


class A(object):
    """
    * 'sectionstatus': { }  # something something something something something something something something
                            # something somethingsomething something POST & DELETE something something.
        * section_id1: { }
            * 'something': 123,  # something something something something something something
            * 'something': int or null,  # Number  something something something something is null if
                                           # Something.property=true.
            * 'something': null/SOMETHING/SOMETHING/SOMETHING,  #  something something in something something.
            * 'something': true/false,  # something something something something something something something
            * 'something': true/false  #  something something in something something's campus 
    """

    a = 1234

    def method(self):
        print "this color is no good"
```

Pictures are worth 1000 words: [broken](http://i.imgur.com/SHiSwk0.png), -> [without the "'s"](http://i.imgur.com/a7E06ah.png)

**Expected behavior:** `a` and the `def method` and the `print` should be syntax highlighted

**Actual behavior:** color breaks after the `'s`

**Reproduces how often:** Every single time

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

I have the latest language-python

```Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

```apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.13
git 2.12.2
```

**Comment by mercutiodesign** [comment] 2017-05-11 09:28
I can confirm this issue of docstrings not ending at the closing quotes.
A very short test case is the following:
```python
def test():
    """
    test `WITH` test
    """
    print('hello')

test()
```

which will display incorrectly as follows:
![screen shot 2017-05-11 at 11 26 41](https://cloud.githubusercontent.com/assets/1114120/25942292/c2e09bf6-363c-11e7-9111-acbdae553597.png)

**Comment by rsese** [comment] 2017-05-11 19:17
I think this is a dupe of https://github.com/atom/language-python/issues/143?  E.g. in both examples, if I disable language-sql as mentioned in https://github.com/atom/language-python/issues/143#issuecomment-238014813, then the highlighting is ok.

**Comment by kingbuzzman** [comment] 2017-05-12 15:43
Confirmed, yes, you're right, if i disable language-sql it works. Sorry for the trouble.

**Closed** 2017-05-12 15:43 UTC

**Comment by rsese** [comment] 2017-05-12 19:02
No problem at all, it took me a bit to put them together :bow:
