### ISSUE TITLE
Editor unable to parse the block docstring with quote and SELECT

### ISSUE THREAD

**Issue by z080320** [atom/language-python#142] opened 2016-04-15 06:36 UTC
The Plugin is not able to parse this code and woould treat the __init__ method as string.
```
class SQLParam:
    """
        "SELECT BUG"
    """
    def __init__(self, value):
        self.value = value
        
```
![screen shot 2016-04-15 at 2 35 50 pm](https://cloud.githubusercontent.com/assets/1487604/14553231/66011b1c-0317-11e6-988b-1c98729a8f8c.png)

**Comment by 50Wliu** [comment] 2016-04-15 12:03
Closing as a duplicate of #110 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-04-15 12:03 UTC
