### ISSUE TITLE
The syntax highlight fails when you use type annotations

### ISSUE THREAD

**Issue by mrkaspa** [atom/language-python#168] opened 2016-11-10 20:17 UTC
<img width="515" alt="screen shot 2016-11-10 at 3 16 31 pm" src="https://cloud.githubusercontent.com/assets/764271/20192656/c6dd90d8-a758-11e6-8d04-d07e99819692.png">

**Comment by 50Wliu** [comment] 2016-11-10 20:21
This is a duplicate of #68 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-11-10 20:21 UTC
