### ISSUE TITLE
inconsistent highlighting of SQL in python files

### ISSUE THREAD

**Issue by bkeepers** [atom/language-python#102] opened 2015-10-07 23:35 UTC
Originally reported by @foresmac in https://github.com/github/linguist/issues/2595:

> Noticed that the syntax highlighting will correctly highlight SQL inside a `cursor.execute()` call, but only if it's a single line.

> Only certain lines recognized here:
> <img width="518" alt="screen shot 2015-08-26 at 2 41 59 pm" src="https://cloud.githubusercontent.com/assets/3628189/9504222/02004cf0-4c01-11e5-9d2d-df82931fb85c.png">

> None recognized here (in a comment marked as `python`):
> <img width="462" alt="screen shot 2015-08-26 at 2 42 28 pm" src="https://cloud.githubusercontent.com/assets/3628189/9504241/1c0d267c-4c01-11e5-83da-15a01fbe7f1a.png">

@pchaigno points out that  it looks like it works if the SQL immediately follows the triple quotes.

```python
example1 = '''
SELECT *
FROM users
WHERE 1 = 1 AND 1 <> 2
'''

example2 = '''SELECT *
FROM users
WHERE 1 = 1 AND 1 <> 2
'''
```

**Comment by auscompgeek** [comment] 2015-10-08 00:50
Seems to be working fine now.

**Comment by foresmac** [comment] 2015-10-08 01:14
So is it the white space/indents that messed it up, or was something changed in SQL highlighting since I reported the issue? I'll try to investigate more when I'm at my desktop.

**Comment by 50Wliu** [comment] 2015-10-08 01:56
Yeah, I can't reproduce this either in Atom, so I'm going to close this.

@foresmac if you manage to reproduce this again be sure to comment here!

**Comment by foresmac** [comment] 2015-10-08 20:06
Just a test:
``` python
def some_func(count):
    cursor.execute('''
        WITH users_with_occurances AS (
        SELECT      users_user.id
                    COUNT(users_user.id) AS occurances
        FROM        users_user
        INNER JOIN  photo_photo
        ON          users_user.id = photos_photo.owner_id
        GROUP BY    users_user.id
        )

        SELECT      COUNT(*)
        FROM        users_with_occurances
        WHERE       occurances >= %s
    ''', [count])
```

**Comment by foresmac** [comment] 2015-10-08 20:07
The first line above doesn't seem to get properly highlighted, though this is much better than what we were getting when I originally reported the issue in late August.

**Comment by foresmac** [comment] 2015-10-08 20:08
Another test:

``` python
cursor.execute('''
    WITH users_with_occurances AS (
    SELECT      users_user.id
                COUNT(users_user.id) AS occurances
    FROM        users_user
    INNER JOIN  photo_photo
    ON          users_user.id = photos_photo.owner_id
    GROUP BY    users_user.id
    )

    SELECT      COUNT(*)
    FROM        users_with_occurances
    WHERE       occurances >= %s
''', [count])
```

**Comment by foresmac** [comment] 2015-10-08 20:09
One more:
``` python
query = '''
    WITH users_with_occurances AS (
    SELECT      users_user.id
                COUNT(users_user.id) AS occurances
    FROM        users_user
    INNER JOIN  photo_photo
    ON          users_user.id = photos_photo.owner_id
    GROUP BY    users_user.id
    )

    SELECT      COUNT(*)
    FROM        users_with_occurances
    WHERE       occurances >= %s
'''
```

**Comment by foresmac** [comment] 2015-10-08 20:11
Ruling out one more variable:

``` python
query = '''
WITH users_with_occurances AS (
SELECT      users_user.id
            COUNT(users_user.id) AS occurances
FROM        users_user
INNER JOIN  photo_photo
ON          users_user.id = photos_photo.owner_id
GROUP BY    users_user.id
)

SELECT      COUNT(*)
FROM        users_with_occurances
WHERE       occurances >= %s
'''
```

**Comment by foresmac** [comment] 2015-10-08 20:11
So, maybe that first line isn't getting recognized because it starts with the `WITH` keyword?

**Comment by foresmac** [comment] 2015-10-08 20:15
Looking at the samples I originally submitted, it looks like the parser is specifically looking for queries to start with a `SELECT`. If the query was composed of individual strings that are auto-concat'ed, only the `SELECT` lines were highlighted. In the sample code I posted above, proper SQL highlighting doesn't start until a `SELECT` is encountered.

<img width="717" alt="screen shot 2015-10-08 at 3 13 14 pm" src="https://cloud.githubusercontent.com/assets/3628189/10378599/645ce328-6dcf-11e5-8b37-0b7eae50e4c3.png">

**Comment by auscompgeek** [comment] 2015-10-09 01:48
I feel that isn't really inconsistent though, it's just a lack of recognising SELECT statements that start with a WITH clause :stuck_out_tongue_winking_eye:

**Comment by foresmac** [comment] 2015-10-09 16:43
Regardless of whether or not you consider it "inconsistent"—that's my characterization of the original issue where _none_ of the SQL was highlighted with the same example code—the syntax highlighting could be improved if the parser recognized queries that didn't start with `SELECT`, right? So, I'll update the issue title to better reflect the current state.

**Comment by foresmac** [comment] 2015-10-09 16:51
CTE's are part of the SQL:1999 standard and have been supported in Postgres [since 8.4](http://www.postgresql.org/docs/8.4/static/queries-with.html); they are also supported in Oracle, MSSQL Server, DB2, and sqlite. Given this, it seems worth supporting the syntax in the highlighter.

**Comment by MichaelAquilina** [comment] 2015-10-10 15:18
WITH is left out from the current SQL grammar rules. Check how an SQL file highlights your queries to see what you mean. 

Current progress to solving this issue:
#105

**Closed** 2015-11-17 16:23 UTC
Labels: bug
