### ISSUE TITLE
Typing module support

### ISSUE THREAD

**Issue by Kolyunya** [atom/language-python#167] opened 2016-11-07 19:56 UTC
It seems to me that the `typing` module support has some issues. The following code has some highlighting problems: decorators and function names are not highlighted correctly.

```python
from abc import ABC, abstractmethod
from typing import List, Tuple


class AbstractFoo(ABC):

    Foo = Tuple[str, str]

    Foos = List[Foo]

    @abstractmethod
    def get_foo(self) -> Foo:
        pass

    @abstractmethod
    def process_foo(self, foo: Foo) -> bool:
        pass

    @abstractmethod
    def process_foos(self, foos: Foos) -> bool:
        pass
```

**Comment by 50Wliu** [comment] 2016-11-07 20:06
This is a duplicate of #68 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-11-07 20:06 UTC
