### ISSUE TITLE
Syntax highlighting bug

### ISSUE THREAD

**Issue by jokingaray** [atom/language-python#172] opened 2016-11-30 14:16 UTC
def buggy_colour(self, **sql_dict):
    ''' Method description.
        'SELECT': select breaks it
    '''
    #Color as comment
    select_= "SELECT " + ("*" if 'SELECT' not in sql_dict else ",".join(map(str,sql_dict['SELECT'])) )
    print 'Regular colour', sql_dict

In the above code, the word 'SELECT' in the method descriptions seems to break the colouring. Code from that point onwards is (moslyt) wrongly coloured (save for 'as', 'not in', 'else' and 'join' as well as =,+). Just removing the final T makes it work OK

![atom_bug](https://cloud.githubusercontent.com/assets/6850127/20755522/90359014-b70f-11e6-965a-cda0d02a4747.png)

**Comment by 50Wliu** [comment] 2016-11-30 18:18
Thanks for taking the time to contribute!

We noticed that this is a duplicate of #110. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by 50Wliu** 2016-11-30 18:18 UTC
