### ISSUE TITLE
Must not highlight backslash chars inside RAW string

### ISSUE THREAD

**Issue by Alexey-T** [atom/language-python#311] opened 2019-10-01 12:16 UTC
I use VSCode latest release, seems it has Atom parser for Python.
Inside raw-strings like 
```
r'some text' 
r"more text"
r'''text'''
r"""text"""
```
editor must ignore `\r`, `\n` etc symbols, because raw-strings don't process them.

Current screen from VSCode: symbols are highlighted

![py-atom](https://user-images.githubusercontent.com/4154978/65961039-6be8fa00-e45e-11e9-931b-8d7f9e98cfae.png)

**Comment by rsese** [comment] 2019-10-01 22:06
Thanks for the report!

Though I can reproduce with Tree-sitter disabled, it looks like this isn't an issue Tree-sitter using Atom 1.40.1:

![python-tree-sitter](https://user-images.githubusercontent.com/734194/66004073-5d560f00-e46d-11e9-93c9-9f5f303da52c.png)

As you may have heard, we are migrating from our old [first-mate grammar engine](https://github.com/atom/first-mate) to the [new Tree-sitter engine](https://blog.github.com/2018-10-31-atoms-new-parsing-system/). This will enable a number of new features, more consistent syntax highlighting, and better performance, among other benefits. In order to free up our limited resources, we have decided to stop maintaining the first-mate grammar when there is a built-in Tree-sitter grammar available. Since this issue applies only to the first-mate grammar, we are going to close it. Please let us know if we have misunderstood the description of the problem.

**Closed by rsese** 2019-10-01 22:06 UTC
