### ISSUE TITLE
Support syntax highlighting for function annotations (PEP 3107)

### ISSUE THREAD

**Issue by wegry** [atom/language-python#68] opened 2015-06-06 04:44 UTC
Currently the following function has it's syntax highlighting broken by having an '->' to hint at the return type of a function (this is valid syntax for Python 3.0 and above, [see here](https://www.python.org/dev/peps/pep-3107/)).

An example:
![screen shot 2015-06-05 at 9 42 08 pm](https://cloud.githubusercontent.com/assets/5156873/8018330/bf72c02c-0bcb-11e5-8e6d-d4b99e139e20.png)

**Comment by auscompgeek** [comment] 2015-07-03 05:54
This also affects annotations on function parameters (supposed to be orange and italics here):

![screenshot from 2015-07-03 15-52-02](https://cloud.githubusercontent.com/assets/128854/8493300/a07ba360-219b-11e5-92e2-501943b65014.png)

**Comment by auscompgeek** [comment] 2015-07-03 06:08
The [PythonImproved](https://github.com/MattDMo/PythonImproved) package by @MattDMo for Sublime Text has support for function annotations, perhaps that might be useful.

**Comment by MattDMo** [comment] 2015-07-04 02:34
Thanks for the mention. Yes, PythonImproved fully supports multiline function annotations with or without embedded comments. I had plans at some point to port it to Atom, and even translated a version into CSON, but I haven't even had a chance to test it, let alone validate it and release it as an Atom package. Also, honestly, I've been playing around with new versions of Atom every once in a while, but I much prefer Sublime for a number of reasons (if you care, go ahead and ask me - I'm quite opinionated :smile: ), and no one has requested an Atom version yet. 

If you do check out Sublime, make sure you get [version 3](http://sublimetext.com/3), even though it still says "Beta" and version 2 is on the home page. There are lots of improvements in 3 over 2, and I've been using 3 pretty much exclusively for over **two years** now, with almost no issues at all (and those that I did have were quite a long time ago, and have since been fixed). It has the same "try before you buy" model that 2 has, in that you can use it for free indefinitely, and it'll just occasionally give you a nag screen and say **`UNREGISTERED`** in the title bar. However, if you like it, I would strongly urge you to buy a license, because you're not only supporting the developer (which is always a good thing), but you get access to the [development builds](http://sublimetext.com/3dev) where the *real* cutting-edge features are previewed and tweaked before making it into the public "beta" version. There's been a **lot** of development that's happened since the end of January, and some really cool features have been added.

Anyways, enough marketing. Try it out, install [Package Control](https://packagecontrol.io) (the *de facto* package manager, Sublime doesn't ship with one), get [Python Improved](https://packagecontrol.io/packages/Python%20Improved), maybe check out my [Neon Color Scheme](https://packagecontrol.io/packages/Neon%20Color%20Scheme) for a prettier Sublime experience, then get coding (and annotating)!

**Comment by MatthewNewland** [comment] 2015-07-30 21:14
You can try:
https://github.com/MatthewNewland/language-python3

**Comment by MrLoh** [comment] 2015-09-13 11:18
any developments on this? Please add support!

**Comment by fjarrett** [comment] 2015-11-27 03:33
This is super annoying.

**Comment by michael-k** [comment] 2015-11-27 09:10
@MatthewNewland Your link is dead. :(

**Comment by auscompgeek** [comment] 2015-11-27 09:36
[MagicPython](https://github.com/MagicStack/MagicPython) exists for now, I guess.

**Comment by alexchandel** [comment] 2016-03-01 15:15
either [MattDMo/PythonImproved](https://github.com/MattDMo/PythonImproved), [MatthewNewland/language-python3](https://github.com/MatthewNewland/language-python3), or [MagicStack/MagicPython](https://github.com/MagicStack/MagicPython) should be copied and merged into this.

**Comment by frewsxcv** [comment] 2016-05-04 14:07
MagicPython works well for me with function annotations.. It also has the same license (MIT). I think it would be easy to just copy the syntax rules and attribute them.

**Comment by 50Wliu** [comment] 2016-05-04 19:25
If someone wants to try to achieve that (or move Python highlighting completely over to MagicPython), please feel free to.  I'd be willing to give advice along the way.  See also #109.

**Comment by 1st1** [comment] 2016-05-10 01:33
I'm one of the MagicPython authors -- would be glad to assist you guys with any kind of integration with Atom.

**Comment by OJFord** [comment] 2016-06-27 09:11
What's the status of this?

Should we be using the MagicPython package? Just confused by @1st1's comment about integrating with Atom when there appears to already be a package.

I've installed it, and it appears to work.. but is this heading for atom/language-python, and I should keep an eye on the changelog? Or use both simultaneously? (Which presently doesn't seem to be causing problems)

**Comment by 50Wliu** [comment] 2016-06-27 15:02
The Atom team is interested in switching `language-python` to use MagicPython.  They haven't decided the best way to do that yet though.  Will see if anything has changed since I last asked (but you'll probably want to subscribe to #109 for future updates).

**Comment by OJFord** [comment] 2016-06-27 15:32
Awesome. Thanks.

FWIW to others - I'm not having any troubles running both side by side; so I plan to continue like this until I hear that it's integrated :)

**Comment by vanillajonathan** [comment] 2016-10-02 15:40
Test case:

```python
def syntax_highlighting_works():
    """Syntax highlighting works."""
    print('Syntax highlighting works.')


def syntax_highlighting_bugs_out() -> None:
    """Syntax highlighting bugs out."""
    print('Syntax highlighting bugs out')
```

**Comment by GabeDottl** [comment] 2017-05-29 16:17
+1 - this bug is super annoying...

**Comment by 1st1** [comment] 2017-05-29 23:43
@GabeDottl Just install MagicPython.

**Comment by dbrgn** [comment] 2017-06-23 11:22
Was a bit stunned that Atom does not support all the Python 3 syntax. Function annotations have been in there for many years now :)

Magic Python works nicely. Would be great to have it in Atom by default. Looks like that discussion is going on in #13877 .

**Closed** 2018-01-25 12:26 UTC
Labels: enhancement, help-wanted

**Comment by 50Wliu** [comment] 2018-01-25 12:34
I have added support for PEP-3107 in #228, which should ship in Atom 1.25 assuming that we do not find any regressions.

I just realized that using expressions as typehints like `max(2, 9)` doesn't quite work yet but I'll try to wrap up support for it soon.
![python-annotations](https://user-images.githubusercontent.com/2766036/35388509-1a25c536-01a2-11e8-852d-ad83c325e051.png)
