### ISSUE TITLE
The editor crashes when I try to open or save a file with .py suffix

### ISSUE THREAD

**Issue by chaoxu95** [atom/language-python#307] opened 2019-06-12 14:50 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
The editor crashes when I try to open or save a file with .py suffix.
When I disable 'language-python' package, this problem disappear.
But I can not use python under atom.
A few hours ago, it runs perfectly. And I did not do anything for atom.
I have the latest version of atom.

### Steps to Reproduce

1. create a new file
2. save it with .py suffix
3. 

**Expected behavior:**

**Actual behavior:**

**Reproduces how often:**

### Versions
mac version : 10.11
atom version: 1.38.0
language-python version: 0.53.1

**Comment by Arcanemagus** [comment] 2019-06-12 16:19
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/atom/issues/19497. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2019-06-12 16:19 UTC
