### ISSUE TITLE
Function Annotation (return type annotation) breaks syntax highlighting

### ISSUE THREAD

**Issue by natec425** [atom/language-python#51] opened 2015-01-24 20:34 UTC
The attached image should be pretty descriptive of the problem. The grammar just doesn't seem to support function annotation. You can see that it doesn't syntax highlight the names/string annotating foo and bar. However, including the return type annotation breaks the syntax highlighting for following sections

![image](https://cloud.githubusercontent.com/assets/1424988/5888889/626f0bbe-a3d5-11e4-9214-32da5ddb315f.png)

**Comment by dveselov** [comment] 2015-03-10 12:35
Any progress on this issue?

**Comment by nbren12** [comment] 2015-07-31 15:03
I am experiencing this as well

**Comment by 50Wliu** [comment] 2015-07-31 15:26
Closing as a duplicate of #68 since that has more discussion on it.

**Closed by 50Wliu** 2015-07-31 15:26 UTC
Labels: bug
