### ISSUE TITLE
Syntax highlighting breaks down

### ISSUE THREAD

**Issue by peterzhu2118** [atom/language-python#237] opened 2018-03-03 16:44 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Python syntax highlighting goes crazy when there are quotes in the docstring. See the issues in this image. There are highlighting problems on lines 1, 2, 6, 7, 11.
![capture](https://user-images.githubusercontent.com/15860699/36936814-06e02536-1ed8-11e8-975d-55d1ac8dcdd6.JPG)

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

```
C:\Users\Peter>atom --version

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0

C:\Users\Peter>apm --version

apm  1.18.12
npm  3.10.10
node 6.9.5 x64
atom 1.24.0
python 2.7.11
git 2.9.0.windows.1
visual studio 2015
```

**Comment by 50Wliu** [comment] 2018-03-05 16:45
Thanks for the issue.  This is in fact caused by language-python not recognizing typehinting, which was fixed in #228 and will be included in future Atom versions.

**Closed by 50Wliu** 2018-03-05 16:45 UTC
