### ISSUE TITLE
Syntax bug

### ISSUE THREAD

**Issue by jplaza** [atom/language-python#190] opened 2017-03-16 09:59 UTC
![image](https://cloud.githubusercontent.com/assets/1086705/23990725/f29f85be-0a04-11e7-8f91-2e26ab908af8.png)

If I just remove the word SELECT (seems like it is displaying it as SQL syntax instead just a method comment string) the code syntax color in the code goes back to normal.

**Comment by rsese** [comment] 2017-03-16 17:44
Thanks for taking the time to contribute!

We noticed that this looks like a duplicate of https://github.com/atom/language-python/issues/110. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-03-16 17:44 UTC
