### ISSUE TITLE
BUG: mis-reads quotes inside docstrings

### ISSUE THREAD

**Issue by nickeubank** [atom/language-python#148] opened 2016-05-17 18:54 UTC
I have a docstring with embedded quotation marks, and the syntax highlighter is getting confused about what's a string and what's not:

![screen shot 2016-05-17 at 11 53 37 am](https://cloud.githubusercontent.com/assets/9683693/15335185/17305642-1c26-11e6-9dce-5456d54b0fbf.png)

Mac OSX

**Comment by StanczakDominik** [comment] 2016-05-28 09:45
That's funny. It works fine like this, with the `S` removed from `SELECT`:
```python
def function(blah):
    """
    Example:
        df = geopandas.GeoDataFrame.from_postgis(con,
        "ELECT geom, highway FROM roads;")
    """
    return 1
```
![screenshot from 2016-05-28 11 42 35](https://cloud.githubusercontent.com/assets/11289391/15626618/5544d4b6-24c9-11e6-8f9b-efb14fc6617a.png)

But add the S back in there and it doesn't register the end of the docstring. Note the `return` changing colour.
```python
def function(blah):
    """
    Example:
        df = geopandas.GeoDataFrame.from_postgis(con,
        "SELECT geom, highway FROM roads;")
    """
    return 1
```
![screenshot from 2016-05-28 11 44 16](https://cloud.githubusercontent.com/assets/11289391/15626624/86a6be02-24c9-11e6-912f-abb5dcc26cba.png)

Is it some conflict with SQL query detection, perhaps?

**Comment by nickeubank** [comment] 2016-05-29 00:33
How very odd. Is there SQL detection in the python module, or is this a
scope detection problem?

**Comment by thomasjo** [comment] 2016-05-29 08:50
This is a duplicate of #143.

**Closed by thomasjo** 2016-05-29 08:50 UTC
