### ISSUE TITLE
Python long comment highlighting error while there's special character.

### ISSUE THREAD

**Issue by kxxoling** [atom/language-python#45] opened 2014-12-09 15:06 UTC
I'm not sure what results in this, but it look wrong here: [Flask helpers.py](https://github.com/mitsuhiko/flask/blob/eca53063862fd487dbce6e36fc42fae80f1494c3/flask/helpers.py#L330)

Fast preview: 
![flask code highlight](https://cloud.githubusercontent.com/assets/1227139/5359396/f16e7220-7ff7-11e4-922c-8f72ab7d3278.png)

**Comment by msabramo** [comment] 2015-01-08 06:23
> in long (tripe-quoted) comments formatting placeholders should not be highlited

:+1:

**Comment by msabramo** [comment] 2015-01-08 15:46
I looked briefly at taking a stab at fixing this last night but I got confused by the grammar.

**Comment by msabramo** [comment] 2015-01-08 15:46
Link to it in Lightshow: https://lightshow.githubapp.com/?utf8=%E2%9C%93&scope=source.python&grammar_url=&grammar_text=&code_source=from-text&code_url=&code=def+get_template_attribute%28template_name%2C+attribute%29%3A%0D%0A++++%22%22%22Loads+a+macro+%28or+variable%29+a+template+exports.++This+can+be+used+to%0D%0A++++invoke+a+macro+from+within+Python+code.++If+you+for+example+have+a%0D%0A++++template+named+%3Afile%3A%60_cider.html%60+with+the+following+contents%3A%0D%0A++++..+sourcecode%3A%3A+html%2Bjinja%0D%0A+++++++%7B%25+macro+hello%28name%29+%25%7DHello+%7B%7B+name+%7D%7D%21%7B%25+endmacro+%25%7D%0D%0A++++You+can+access+this+from+Python+code+like+this%3A%3A%0D%0A++++++++hello+%3D+get_template_attribute%28%27_cider.html%27%2C+%27hello%27%29%0D%0A++++++++return+hello%28%27World%27%29%0D%0A++++..+versionadded%3A%3A+0.2%0D%0A++++%3Aparam+template_name%3A+the+name+of+the+template%0D%0A++++%3Aparam+attribute%3A+the+name+of+the+variable+of+macro+to+access%0D%0A++++%22%22%22%0D%0A++++return+getattr%28current_app.jinja_env.get_template%28template_name%29.module%2C%0D%0A+++++++++++++++++++attribute%29

**Comment by Arcanemagus** [comment] 2018-03-16 17:52
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-python/issues/40. Although there are a few more comments here, the issue is better described over in #40. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by Arcanemagus** 2018-03-16 17:52 UTC
Labels: bug
