### ISSUE TITLE
Multiline arguments doesn't auto-indent

### ISSUE THREAD

**Issue by NDavidBrown** [atom/language-python#73] opened 2015-06-29 11:26 UTC
For example:

```
def should_look_like_this(arg1=None,
                          arg2=None):
    pass
```
but you actually get:
```
def actually_looks_like_this(arg1=None,
arg2=None):
pass
```

**Comment by NDavidBrown** [comment] 2015-06-29 12:22
..furthermore, this doesn't apply only to function definitions, but rather to general code.

For example, you see the same issue of not matching the preceding line indentation when splitting args onto newlines to avoid exceeding 80 chars in this example:

```
linematch_regex = r'%s %d IN %s %s'%(key or default_match,
ttl,
rtype,
value)'
```

You would instead expect it to look like this, as it does in most other editors I experiment with:

```
linematch_regex = r'%s %d IN %s %s'%(key or default_match,
                                                            ttl,
                                                            rtype,
                                                            value)'
```

**Comment by NDavidBrown** [comment] 2015-06-29 13:17
This is a real deal breaker for me - you guys have by default included an 80 char line symbol to encourage coders to keep code line lengths under 80 chars, yet this basic mechanism to do so - splitting arguments onto newlines - is not supported by the indenter!

I really like Atom but this and the other indentation issue I've reported mean I cannot use it regularly yet, which is disappointing. It's just too time-consuming to overcome these issues manually when you're a fast coder, unfortunately.

**Comment by brianmhunt** [comment] 2015-07-30 15:11
Is this not a duplicate of #22?

**Comment by lzkelley** [comment] 2015-10-18 22:11
This is definitely a duplicate of #22

**Comment by thomasjo** [comment] 2015-10-18 22:22
Closing as this is essentially a duplicate of #22 (as pointed out by @brianmhunt and @lzkelley).

**Closed by thomasjo** 2015-10-18 22:22 UTC
Labels: auto-indent
