### ISSUE TITLE
Failed to load a language-python package grammar

### ISSUE THREAD

**Issue by elyaraujo** [atom/language-python#203] opened 2017-06-18 23:45 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [language-python](https://github.com/atom/language-python) package 0.45.2

### Stack Trace

Failed to load a language-python package grammar

```
At ENOENT: no such file or directory, open 'C:\Users\ely.christie\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-python\grammars\regular expressions (python).json' in C:\Users\ely.christie\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-python\grammars\regular expressions (python).json

Error: ENOENT: no such file or directory, open 'C:\Users\ely.christie\AppData\Local\atom\app-1.18.0\resources\app\node_modules\language-python\grammars\regular expressions (python).json'
    at Error (native)
  at ~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/language-python/grammars/regular expressions (python).json:1:1
```

### Commands

```
```

### Non-Core Packages

```
color-picker 2.0.14 
minimap 4.19.0 
pigments 0.19.5 
```

**Comment by rsese** [comment] 2017-06-19 09:52
Closing per https://github.com/atom/language-ruby-on-rails/issues/55#issuecomment-309392781

**Closed by rsese** 2017-06-19 09:52 UTC

**Comment by agusmakmun** [comment] 2017-12-06 22:35
This issue is similiar with my problem after updating the `language-python` package. but, got a different message wich following:

```
Grammar missing required scopeName property: /home/agaust/.atom/packages/language-python/grammars/tree-sitter-python.cson in /home/agaust/.atom/packages/language-python/grammars/tree-sitter-python.cson

Hide Stack Trace

Error: Grammar missing required scopeName property: /home/agaust/.atom/packages/language-python/grammars/tree-sitter-python.cson
    at /opt/atom/resources/app.asar/node_modules/first-mate/lib/grammar-registry.js:122:64
    at /opt/atom/resources/app.asar/node_modules/season/lib/cson.js:197:59
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
  at /home/agaust/.atom/packages/language-python/grammars/tree-sitter-python.cson:1:1
```

**Comment by ThinkDigitalRepair** [comment] 2017-12-15 00:53
Getting this issue as well. I just updated 3 packages, one of which was atom-ide-ui.
`Error: Grammar missing required scopeName property: /home/thinkdigital/.atom/packages/language-python/grammars/tree-sitter-python.cson
    at /usr/share/atom-beta/resources/app/node_modules/first-mate/lib/grammar-registry.js:123:70
    at parseContents (/usr/share/atom-beta/resources/app/node_modules/season/lib/cson.js:123:13)
    at /usr/share/atom-beta/resources/app/node_modules/season/lib/cson.js:226:30
    at FSReqWrap.oncomplete (fs.js:112:15)
  at /home/thinkdigital/.atom/packages/language-python/grammars/tree-sitter-python.cson:1:1`

**Comment by rsese** [comment] 2017-12-15 01:33
@agusmakmun the latest release version of Atom is 1.23.1 - go ahead and install Atom with the official .deb from https://atom.io and let us know if you still have trouble.

@ThinkDigitalRepair it looks like language-python was somehow installed manually on your system.  It's a core package so shouldn't be installed like that - go ahead and run `apm uninstall language-python` and let us know if that doesn't help.

**Comment by ThinkDigitalRepair** [comment] 2017-12-15 01:35
When I try that, I get `No APM support in kernel`

**Comment by rsese** [comment] 2017-12-15 02:03
I poked around and found:

https://github.com/atom/atom/issues/3926

Seems like a name conflict with an installed package on your system? 

But I also noticed that it looks like you're running the beta?  If so, can you try `apm-beta uninstall language-python`?  It also looks like you can't uninstall the manually installed version from Settings (there's no uninstall button in that case).

**Comment by agusmakmun** [comment] 2017-12-15 04:15
@rsese thank for your recomendation... but currently I working on 32bit, not 64bit.. is there any option please?

**Comment by ThinkDigitalRepair** [comment] 2017-12-15 05:19
Using apm-beta fixed it. Thank you. does that mean I can't use this package or just reinstall it?

**Comment by rsese** [comment] 2017-12-15 22:23
> but currently I working on 32bit, not 64bit.. is there any option please?

Sorry @agusmakmun, the official Atom installers are only officially supported for 64-bit Linux systems:

https://github.com/atom/atom/#debian-based-debian-ubuntu-linux-mint

Building from source may be an option though?

https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#platform-linux

> Using apm-beta fixed it. Thank you. does that mean I can't use this package or just reinstall it?

@ThinkDigitalRepair you can still use the package, it's a core package that comes with Atom by default.  There's no need to install it manually and we just removed the extra manual install.

**Comment by anshayea** [comment] 2018-01-28 15:31
I'm still facing the same bug, 
this is the error message: " 

Grammar missing required scopeName property: /Users/{username}/.atom/packages/language-python/grammars/tree-sitter-python.cson in /Users/{username}/.atom/packages/language-python/grammars/tree-sitter-python.cson

Error: Grammar missing required scopeName property: /Users/{username}/.atom/packages/language-python/grammars/tree-sitter-python.cson
    at /Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:128:70
    at /Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:223:65
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
  at /Users/{username}/.atom/packages/language-python/grammars/tree-sitter-python.cson:1:1

"

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.3
**Thrown From**: [language-python](https://github.com/atom/language-python) package 0.48.0


### Stack Trace

Failed to load a language-python package grammar

```
At Grammar missing required scopeName property: /Users/Abdul-Rahman/.atom/packages/language-python/grammars/tree-sitter-python.cson in /Users/Abdul-Rahman/.atom/packages/language-python/grammars/tree-sitter-python.cson

Error: Grammar missing required scopeName property: /Users/Abdul-Rahman/.atom/packages/language-python/grammars/tree-sitter-python.cson
    at /Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:128:70
    at /Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:223:65
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
  at /packages/language-python/grammars/tree-sitter-python.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.30.9 
atom-django 0.3.2 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
chester-atom-syntax 0.3.0 
color-picker 2.2.5 
dash 1.7.1 
django-atom 0.2.4 
django-templates 0.5.0 
dusk-syntax 2.0.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.16 
git-control 0.9.0 
git-plus 7.10.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-django 0.1.1 
linter 2.2.0 
linter-flake8 2.3.0 
linter-pycodestyle 2.1.3 
linter-ui-default 1.6.10 
linter-write-good 0.9.0 
minimap 4.29.7 
pigments 0.40.2 
platformio-ide-terminal 2.8.0 
predawn-syntax 1.0.4 
python-autopep8 0.1.3 
python-debugger 0.2.0 
python-tools 0.6.9 
refactor 0.11.5 
script 3.17.3 
symbols-tree-view 0.14.0 
todo-show 2.1.0 
xcode-true-dusk-syntax 0.1.0 
```

**Comment by 50Wliu** [comment] 2018-01-28 15:58
Uninstall language-python so that Atom will use its builtin version.

**Comment by anshayea** [comment] 2018-01-29 05:18
there is no option to "Uninstall"

<img width="772" alt="screen shot 2018-01-29 at 08 17 09" src="https://user-images.githubusercontent.com/3684472/35494614-d8f2eeb2-04cc-11e8-943b-13659e00adb1.png">

**Comment by 50Wliu** [comment] 2018-01-29 21:38
Ah, I forgot.  You'll need to uninstall it from the command line: `apm uninstall language-python`.

**Comment by anshayea** [comment] 2018-01-31 19:00
Thanks, it's working now
