### ISSUE TITLE
not correct highlight

### ISSUE THREAD

**Issue by Edenharder** [atom/language-python#163] opened 2016-10-22 17:18 UTC
![image](https://cloud.githubusercontent.com/assets/6672134/19621172/47d7eb38-988c-11e6-8f6f-87fe1367f70e.png)
same syntax but has different highlight. I have changed many themes but the same issue, so I think it's the problem of python language.

**Comment by 50Wliu** [comment] 2016-10-23 15:50
This is a duplicate of atom/atom#1667 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-10-23 15:50 UTC
