### ISSUE TITLE
Error: spawn pylint ENOENT

### ISSUE THREAD

**Issue by diazgilberto** [atom/language-python#153] opened 2016-08-22 02:57 UTC
I just did a clean install of "El Capitan" and I'm setting up my development environment back. I install Atom and the plugins I had before and I'm getting this error message. I played around with the pep8 and pyling by switching on and off, and seems to be language-python the problem. When I disable language-python the error goes away. I also try other python syntax highlighter and the error still occur. 
What could be the problem?

![screen shot 2016-08-21 at 9 52 02 pm](https://cloud.githubusercontent.com/assets/9165819/17842541/91fc8274-67e9-11e6-9cc2-61288e07b221.png)

**Comment by thomasjo** [comment] 2016-08-22 07:20
This is caused by one of your community packages. You can verify this by starting Atom in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode). The reason it seems as if its caused by language-python is that the problematic package is most likely activated based on the Python grammar. When language-python is disabled, the grammar isn't set, hence the problematic package does not activate (or at least does not attempt to lint your document).

Without knowing more, it's very hard to help you track down the problem. I am guessing this is caused by the linter-pylint package. Most likely because because you haven't installed underlying pylint executable correctly.

Since the problem is not caused by this package, I'm closing the issue.

PS. In the future, please consider submitting [more detailed bug reports](https://github.com/atom/atom/blob/579e6b23cfa7724637d70f03e918e809c2a55ffc/CONTRIBUTING.md#how-do-i-submit-a-good-bug-report)

**Closed by thomasjo** 2016-08-22 07:20 UTC
