### ISSUE TITLE
Python 3 type hints break syntax highlighting

### ISSUE THREAD

**Issue by lexicalunit** [atom/language-python#132] opened 2016-02-11 21:45 UTC
# Before
![before](https://cloud.githubusercontent.com/assets/1903876/12991752/4cf3f6f8-d0d6-11e5-94d6-5e47e2e3fc5c.png)

# After
![after](https://cloud.githubusercontent.com/assets/1903876/12991751/4cf3c304-d0d6-11e5-83fe-ceac36ba2f67.png)

**Comment by 50Wliu** [comment] 2016-02-11 22:05
This is a duplicate of #68 - feel free to subscribe there for updates.

**Closed by 50Wliu** 2016-02-11 22:05 UTC
