### ISSUE TITLE
Syntax highlighting issue when declaring return type

### ISSUE THREAD

**Issue by sybrenstuvel** [atom/language-python#192] opened 2017-04-14 08:38 UTC
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Code following a `def` with return type declaration (`def func() -> str`) fails to highlight properly.

### Steps to Reproduce

1. Copy the code below into an xxx.py file and open it in Atom.
2. See the wrong highlighting
3. Remove the ` -> str` return type declaration
4. See the correct highlighting

The code:

```python
def func() -> str:
    """This is a docstring that is not highlighted properly"""

def otherfunc():
    """This entire function is highlighted incorrectly.

    The docstring is fine, though, now that we've seen
    a def without return type declaration."""
```

Screenshots of bad resp. correct highlighting.

![screenshot of bad highlighting](https://cloud.githubusercontent.com/assets/1092128/25038237/f176bfee-20fd-11e7-9d00-3206687570c5.png)

![screenshot of correct highlighting](https://cloud.githubusercontent.com/assets/1092128/25038247/04b2184c-20fe-11e7-81e2-c596a2d2ac33.png)

**Expected behavior:**

I would expect the syntax highlighting of the code to be correct when I use syntactically correct Python.

**Actual behavior:**

The syntax highlighting is broken (see screenshots above) when a return type is declared.

**Reproduces how often:**

100% of the time.

### Versions

Atom    : 1.16.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.12+
git 2.9.3

Running on Kubuntu Linux 16.10, kernel 4.8.0-46-generic

**Comment by rsese** [comment] 2017-04-14 17:23
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-python/issues/68. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-04-14 17:23 UTC
