### ISSUE TITLE
Atom freeze while open large file on Mac

### ISSUE THREAD

**Issue by orklann** [atom/language-python#284] opened 2018-11-08 08:09 UTC
### Description

Atom freezes forever while opening this a little large python snippets (see my upload) 

### Steps to Reproduce

1. Install newest Atom on Mac
2. Open the python file I upload
3. Atom freeze

### Versions
Atom version: 1.32.1
OS: macOS 10.14

[autocomplete.py.zip](https://github.com/atom/language-python/files/2560796/autocomplete.py.zip)

**Comment by Aerijo** [comment] 2018-11-08 08:12
/cc @maxbrunsfeld 

I could reproduce with the provided file on Stable and Beta. The tree sitter parser itself reports ~380ms when running `tree-sitter parse examples/autocomplete.py -q`, so it seems the issue is with Atom. When Tree-sitter is disabled, everything works fine.

**Comment by Aerijo** [comment] 2018-11-08 10:32
Also adding it's much reduced on Nightly 1.34.0-11; there is a small freeze that is not present when using textmate, but it quickly becomes just as responsive.

I'll leave this open, as that slight freeze is still undesirable, but at least it seems the main issue is fixed.

**Comment by Ben3eeE** [comment] 2018-11-08 10:35
Possibly related to https://github.com/atom/atom/issues/18342 which has been fixed on master/nightly. It's still open to investigate other issues with ERB.

**Comment by maxbrunsfeld** [comment] 2018-11-09 06:00
I believe this is fixed. The fix will ship tomorrow morning in Atom 1.32.2.

**Closed by maxbrunsfeld** 2018-11-09 06:00 UTC
Labels: tree-sitter
