### ISSUE TITLE
Unable to match language_variables in function paramaters

### ISSUE THREAD

**Issue by youzhonghui** [atom/language-python#129] opened 2016-01-18 13:04 UTC
I want to custom a syntax to highlight the keyword 'self' / 'cls' in function paramater place. But the gramma dose not support.

**Comment by ValarDragon** [comment] 2017-05-19 18:05
This is a duplicate of issue #99

**Comment by 50Wliu** [comment] 2017-05-20 03:26
Thanks @ValarDragon!

**Closed by 50Wliu** 2017-05-20 03:26 UTC
Labels: enhancement
