### ISSUE TITLE
REPLACE in docstring breaks highlighting

### ISSUE THREAD

**Issue by cod3monk** [atom/language-python#219] opened 2017-12-05 15:24 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Having a triple-quoted docstring which contains `'REPLACE'` or `"REPLACE"` breaks highlighting until end of file.

### Steps to Reproduce

1. New file
2. Select python highlighting
3. Insert
```python
def bar():
    ''' 'REPLACE' '''
    test = 123
    pass
```
or
```python
def bar():
    ''' 'REPLACE' '''
    test = 123
    pass
```
(works with any combination of single or double quotes, although the effect might differ slightly)

**Expected behavior:**
Correct formatting after termination of tripple quoted section.

**Actual behavior:**
Either all or most of the remaining code is highlighted as string.

**Reproduces how often:**
Always.

### Versions

```
$ atom --version
Atom    : 1.22.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
$ apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 3.5.4
git 2.15.0
$
```

**Comment by rsese** [comment] 2017-12-05 18:23
Thanks for taking the time to contribute!

We noticed that this is a duplicate of https://github.com/atom/language-python/issues/110. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

For information on how to use GitHub's search feature to find out if something is a duplicate before filing, see [the How Can I Contribute? section of the Atom CONTRIBUTING guide](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#how-can-i-contribute).

**Closed by rsese** 2017-12-05 18:23 UTC
